name: angular_playground
description: A sample web application
dependencies:
  browser: any
  angular: '>=0.10.0 <0.11.0'

#    git: git@github.com:angular/angular.dart.git
  web_components: any

transformers:
#- angular:
#  template_uri_rewrites:
#    packages/: /packages/

  - $dart2js: {'minify': true}

