name: angular_playground
description: A sample web application
dependencies:
  browser: any
  angular: '>=0.9.10'

#    git: git@github.com:angular/angular.dart.git
  shadow_dom: any

transformers:
- angular:
    template_uri_rewrites:
      packages/: /packages/

